### ISSUE TITLE
ansible-omnibus-gitlab-playbook だと思ったら違った件(I have been missing a playbook )

### ISSUE THREAD

**Issue by ynott** [attakei/ansible-omnibus-gitlab-sample#1]
I saw this presentation article.
このプレゼンテーションを見ました。
Ansibleで作る、AWSで「器の大きい」Omnibus-GitLab // Speaker Deck
https://speakerdeck.com/attakei/ansibletezuo-ru-awste-qi-falseda-kii-omnibus-gitlab

But there is no files found.
しかし、ここにはファイルがなかった。

So Sad.
残念です。

Do you have the source code of ansible-omnibus-gitlab-playbook in any other place?
ansible-omnibus-gitlab-playbook のコースコードはどこか別の場所にありますか？

**Comment by attakei** [comment]
@ynott 
Currently, playbook is managed on GitLab.com .
In furure, I will mirror it from GitLab.
If you want see soon, Check https://gitlab.com/attakei/ansible-omnibus-gitlab-playbook/
(and sorry, repository was private until now. )


現在、PlaybookはGitLab.comで管理しています。
近いうちにGitHub側にもミラーリングする予定はありますが、
すぐに見たい場合は https://gitlab.com/attakei/ansible-omnibus-gitlab-playbook/ を参照してください。
(ついさっきまで、公開設定がprivateになってました。失礼しました)

**Comment by ynott** [comment]
@attakei 
👍   💯  😃  🚪
